### ISSUE TITLE
be_kind_of cannot be used without expect clause

### ISSUE THREAD

**Issue by kalabiyau** [SUSE/TeamDashboard#1]
As in RSpec we always need an expect clause to test that condition is met - we need to fix following lines:

https://github.com/NadjaW/TeamDashboard/blob/master/spec/models/user_spec.rb#L29
https://github.com/NadjaW/TeamDashboard/blob/master/spec/models/user_spec.rb#L37
https://github.com/NadjaW/TeamDashboard/blob/master/spec/models/user_spec.rb#L51
https://github.com/NadjaW/TeamDashboard/blob/master/spec/models/user_spec.rb#L65
https://github.com/NadjaW/TeamDashboard/blob/master/spec/models/user_spec.rb#L77
https://github.com/NadjaW/TeamDashboard/blob/master/spec/models/user_spec.rb#L81

Idea is to save one record, then test what is the type of attribute. Something like:

```ruby
user = User.create!(....parameters...)
expect(user.<attribute name>).to be_kind_of String
```

<attribute name> is just a placeholder for attribute name

**Comment by NadjaW** [comment]
Hey Artem,

Vlad helped me with tests Line 74 and 80. He mentioned that it is not that necessary to test attributes which are automatically generated from Rails. Do you share this opinion?

**Comment by kalabiyau** [comment]
@NadjaW in general he is right, but for learning purpose it is fine to understand how and what you can test.

**Comment by kalabiyau** [comment]
yes, I do, as they are usually defined as database types. So we can close this :)
